# Generated by Django 3.1.7 on 2021-03-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='hotel.rooms'),
            preserve_default=False,
        ),
    ]
