# Generated by Django 3.1.7 on 2021-03-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20210323_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='hotel.rooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
