# Generated by Django 3.1.7 on 2021-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210324_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
