# Generated by Django 3.1.7 on 2021-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
