# Generated by Django 3.1.7 on 2021-03-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_guest_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.customer'),
        ),
    ]
