# Generated by Django 3.1.7 on 2021-03-25 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20210324_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
