# Generated by Django 3.1.7 on 2021-03-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_booking_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
    ]
