# Generated by Django 3.1.7 on 2021-03-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20210324_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotel.booking'),
        ),
    ]
