# Generated by Django 3.1.7 on 2021-03-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
