# Generated by Django 3.1.7 on 2021-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_booking_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
