# Generated by Django 3.1.7 on 2021-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20210325_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_amount',
            field=models.FloatField(null=True),
        ),
    ]
