# Generated by Django 3.1.7 on 2021-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_booking_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
